events {}

http {
  upstream auth_service { server auth_service:8001; }
  upstream detection_service { server detection_service:8002; }
  upstream ml_training_service { server ml_training_service:8003; }
  upstream monitoring_service { server monitoring_service:8004; }
  upstream dashboard_service { server dashboard_service:8005; }
  upstream admin_service { server admin_service:8006; }

  server {
    listen 8000;

    location /auth/ { proxy_pass http://auth_service; }
    location /detect/ { proxy_pass http://detection_service; }
    location /train/ { proxy_pass http://ml_training_service; }
    location /monitor/ { proxy_pass http://monitoring_service; }
    location /dashboard/ { proxy_pass http://dashboard_service; }
    location /admin/ { proxy_pass http://admin_service; }
  }
}

